create table player_field
(
pTeam varchar(50) not null,
pYear smallint not null,
pName varchar(50) not null,
age smallint,
g smallint,
gs smallint,
cg smallint,
inn decimal,
ch smallint,
po smallint,
a smallint,
e smallint,
dp smallint,
fld decimal,
rTot smallint,
rTotYr smallint,
rDrs smallint,
rDrsYr smallint,
rf9 decimal,
rfG decimal,
pb smallint,
wp smallint,
sb smallint,
cs smallint,
csP varchar(5),
lgCS varchar(5),
pickOff smallint,
posSum varchar(50)
);