create table player_hit
(
pTeam varchar(50) not null,
pYear smallint not null,
pos varchar(5),
pName varchar(50) not null,
age smallint,
g smallint,
pa smallint,
ab smallint,
r smallint,
h smallint,
doubles smallint,
triples smallint,
hr smallint,
rbi smallint,
sb smallint,
cs smallint,
bb smallint,
so smallint,
ba decimal,
obp decimal,
slg decimal,
ops decimal,
opsPlus decimal,
tb smallint,
gdp smallint,
hbp smallint,
sh smallint,
sf smallint,
ibb smallint
);